keyboard: Add missing polkit dependency in meson build
Completes: b34ec1bec8cfc4540471fb0805f29af32e5721f9.

Fixes NixOS build:

FAILED: [code=1] panels/keyboard/libkeyboard.a.p/cc-input-list-box.c.o
gcc -Ipanels/keyboard/libkeyboard.a.p -Ipanels/keyboard -I../panels/keyboard -I. -I.. -Ipanels/common -I../panels/common -I/nix/store/50fnfi2484nn8dzbh7ric41a96ml3581-glib-2.86.3-dev/include -I/nix/store/50fnfi2484nn8dzbh7ric41a96ml3581-glib-2.86.3-dev/include/glib-2.0 -I/nix/store/fgzpllmvbk3l258j0f3ib7k44lksbqnp-glib-2.86.3/lib/glib-2.0/include -I/nix/store/kp04kh3bxdajlkjlma0nw9dp35l1d44h-gsettings-desktop-schemas-50.beta/include/gsettings-desktop-schemas -I/nix/store/db0gw9f3w984im1s8y0wcrk4gg9r7bni-gtk4-4.21.5-dev/include/gtk-4.0 -I/nix/store/bvk4cw5w1h1nw6fy1z7zn2hqkvcc6d2i-cairo-1.18.4-dev/include/cairo -I/nix/store/d4i1vzn8wsna9rjcc2h55qcsnd8mg815-freetype-2.13.3-dev/include/freetype2 -I/nix/store/d4i1vzn8wsna9rjcc2h55qcsnd8mg815-freetype-2.13.3-dev/include -I/nix/store/4ndhnsp212zd65c80yvs9dvyhdkxndj7-gdk-pixbuf-2.44.4-dev/include/gdk-pixbuf-2.0 -I/nix/store/pxflbf7xxl2z11q32c7cqfi41b3w5v8p-graphene-1.10.8-dev/include/graphene-1.0 -I/nix/store/shs7lb1n1d7d1jb9cdlqsgpjxdgr83av-graphene-1.10.8/lib/graphene-1.0/include -I/nix/store/3rb207jds7cqrr59x8yi7h44d7q8s0hm-pango-1.57.0-dev/include/pango-1.0 -I/nix/store/x5ydpx2a4pcgzl5y0qklvr3znkdc3ab2-harfbuzz-12.3.0-dev/include/harfbuzz -I/nix/store/lhzl3zl3mfl46grkmxda6j5921bki81j-vulkan-headers-1.4.335.0/include -I/nix/store/4507slwmg0w51agap3aglqbpgsr6ikyk-libadwaita-1.9.beta-dev/include/libadwaita-1 -I/nix/store/50fnfi2484nn8dzbh7ric41a96ml3581-glib-2.86.3-dev/include/gio-unix-2.0 -I/nix/store/0lf9m1rzrwngp42gil39283c7nm6w35m-accountsservice-23.13.9-dev/include/accountsservice-1.0 -I/nix/store/fxq3n2anjrfg3jwwvfx5iw49smgdax65-gnome-desktop-44.5-dev/include/gnome-desktop-4.0 -I/nix/store/vpfqc5dfqhhvpp8mjjc702mwlxl9zqxy-ibus-1.5.33-dev/include/ibus-1.0 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -DHAVE_CONFIG_H -Wno-deprecated-declarations -Wno-unused-parameter -fPIC -mfpmath=sse -msse -msse2 -pthread -mfpmath=sse -msse -msse2 '-DG_LOG_DOMAIN="cc-keyboard-panel"' '-DPANEL_ID="keyboard"' '-DKEYBOARD_PREVIEWER_EXEC="/nix/store/di6khp47g7paj68cr10hm3c8d5vxjx3x-tecla-49.0/bin/tecla"' -MD -MQ panels/keyboard/libkeyboard.a.p/cc-input-list-box.c.o -MF panels/keyboard/libkeyboard.a.p/cc-input-list-box.c.o.d -o panels/keyboard/libkeyboard.a.p/cc-input-list-box.c.o -c ../panels/keyboard/cc-input-list-box.c
../panels/keyboard/cc-input-list-box.c:36:10: fatal error: polkit/polkit.h: No such file or directory
   36 | #include <polkit/polkit.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.