tests: Temporarily disable network panel test
Due to CI issues:
3/6 gnome-control-center:test-network-panel  FAIL             1.02s   exit status 1
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
(/builds/GNOME/gnome-control-center/_builddir/tests/network/test-network-panel:3855): Gdk-WARNING **: 08:48:40.848: Cannot get portal org.freedesktop.portal.Settings version: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.Settings”
Execution of GTest executable to query the tests returned non-zero exit code!
Error generating separate test funcs, will call binary once.
test_all (__main__.PanelTestCase.test_all) ... TAP version 14
 random seed: R02Sd1e0dcd469cfae0eafab05f47c8a3bb8
libEGL warning: DRI3 error: Could not get DRI3 device
libEGL warning: Ensure your X server supports DRI3 to get accelerated rendering
 GVFS-DEBUG: org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gtk.vfs.Daemon was not provided by any .service files (g-dbus-error-quark, 2)

 GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
 Adwaita-DEBUG: Portal not found: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
 Adwaita-DEBUG: Portal not found: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
 Adwaita-DEBUG: Portal not found: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
 Adwaita-DEBUG: Portal not found: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
 GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation memory (GMemorySettingsBackend) for ‘gsettings-backend’
(/builds/GNOME/gnome-control-center/_builddir/tests/network/test-network-panel:3963): Gtk-WARNING **: 08:48:41.317: Use GtkSettings:gtk-interface-color-scheme instead
ERROR
======================================================================
ERROR: test_all (__main__.PanelTestCase.test_all)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/GNOME/gnome-control-center/tests/network/../shared/gtest.py", line 117, in _gtest_all
    subprocess.check_call([self.g_test_exe], timeout=self.g_test_all_timeout)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/subprocess.py", line 419, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/builds/GNOME/gnome-control-center/_builddir/tests/network/test-network-panel']' died with <Signals.SIGABRT: 6>.
----------------------------------------------------------------------
Ran 1 test in 0.769s
FAILED (errors=1)
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Summary of Failures:
3/6 gnome-control-center:test-network-panel  FAIL             1.02s   exit status 1
Ok:                5
Fail:              1
Full log written to /builds/GNOME/gnome-control-center/_builddir/meson-logs/testlog.txt
Mutter terminated with a failure: The command exited with a nonzero status: 256
Gdk-Message: 08:48:41.778: Error reading events from display: Broken pipe
libmutter-Message: 08:48:41.783: Removed virtual monitor Meta-0
A connection to the bus can't be made