network: include generated resource header files in the panel dep
This should fix a rare race where the network tests panel has its
sources compiled before the network resources are generated. Per the
meson documentation sources in declare_dependency: "sources to add to
targets (or generated header files that should be built before sources
including them are built)". Without the sources, the dependency makes
sure that the global shortcuts will not be linked until the dependency
is ready, but some of its files might be compiled before the header is
ready.

Example error:
https://gitlab.alpinelinux.org/fossdd/aports/-/jobs/1872469

ninja: job failed: cc -Itests/network/test-wifi-panel-text.p -Itests/network -I../tests/network -I. -I.. -Ipanels/network -I../panels/network -I../tests/network/nm-utils -Ipanels/common -I../panels/common -Ishell -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gsettings-desktop-schemas -I/usr/include/libadwaita-1 -I/usr/include/gtk-4.0 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/webp -I/usr/include/cairo -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/graphene-1.0 -I/usr/lib/graphene-1.0/include -I/usr/include/fribidi -I/usr/include/appstream -I/usr/include/gio-unix-2.0 -I/usr/include/libnm -I/usr/include/libnma -I/usr/include/libmm-glib -I/usr/include/ModemManager -flto=auto -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -DHAVE_CONFIG_H -Wno-deprecated-declarations -Os -fstack-clash-protection -Wformat -Werror=format-security -g -fPIE -pthread '-DTEST_SRCDIR="/builds/fossdd/aports/community/gnome-control-center/src/gnome-control-center-48.2/tests/network"' -DNETWORKMANAGER_COMPILATION=NM_NETWORKMANAGER_COMPILATION_WITH_GLIB -DNETWORKMANAGER_COMPILATION_TEST '-DTEST_NM_SERVICE="/builds/fossdd/aports/community/gnome-control-center/src/gnome-control-center-48.2/tests/network/nm-utils/test-networkmanager-service.py"' -MD -MQ tests/network/test-wifi-panel-text.p/test-wifi-text.c.o -MF tests/network/test-wifi-panel-text.p/test-wifi-text.c.o.d -o tests/network/test-wifi-panel-text.p/test-wifi-text.c.o -c ../tests/network/test-wifi-text.c
In file included from ../tests/network/test-wifi-text.c:34:
../panels/network/cc-wifi-panel.c:20:10: fatal error: cc-network-resources.h: No such file or directory
   20 | #include "cc-network-resources.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~